title: Blog
description: Blog for Electronics | Embeeded | Firmware | Software

url: https://farogh007.github.io/Blog
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: Farogh007
   twitter: 
   facebook: farogh.iftekhar
   email: farogh007@gmail.com

google_analytics: ""
